<a href="https://colab.research.google.com/github/hj-1006/devasc-study-team/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%EC%99%80_%ED%8C%90%EB%8B%A4%EC%8A%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
a = np.array(range(10)).reshape((2,5))
b = a.transpose()
print('a\n',a)
print('b\n',b)


a
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [12]:
#6-7 배열로 마스킹
mask = np.array([0, 1, 1, 0], dtype = bool)
print(mask)

data = np.random.randn(4,2)
print('\data 출력 \n',data)

print('\n 마스킹된 데이터 출력\', data[mask]')
print('\n마스킹 역전된 데이터 출력\' , data[~mask]')

[False  True  True False]
\data 출력 
 [[-0.90596047  1.48884072]
 [-0.46336123 -1.90780515]
 [ 1.21193413 -0.86764011]
 [-0.36443313 -0.51555399]]

 마스킹된 데이터 출력', data[mask]

마스킹 역전된 데이터 출력' , data[~mask]
